# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/myimg/no_img.jpg', upload_to='Images/'),
        ),
    ]
