# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/no_img.jpg', upload_to='Images/'),
        ),
    ]
