# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180509_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='Images/no_img.jpg', null=True, upload_to='Images/'),
        ),
    ]
